// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYQizWc7pVR5mUUmbNx75h6P2meGybPSw',
    appId: '1:381769684680:web:a89f8f55c511c0a70737fd',
    messagingSenderId: '381769684680',
    projectId: 'business-app-f6f9b',
    authDomain: 'business-app-f6f9b.firebaseapp.com',
    databaseURL: 'https://business-app-f6f9b-default-rtdb.firebaseio.com',
    storageBucket: 'business-app-f6f9b.firebasestorage.app',
    measurementId: 'G-04J41XTP1W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChhU6Psic24uhEeBtQpUOiZ5idJ0br0Tk',
    appId: '1:381769684680:android:d600d39ccc9c9f060737fd',
    messagingSenderId: '381769684680',
    projectId: 'business-app-f6f9b',
    databaseURL: 'https://business-app-f6f9b-default-rtdb.firebaseio.com',
    storageBucket: 'business-app-f6f9b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfj_M34n9Bk6oPQl_fBlDdyOdR-1mfaxA',
    appId: '1:381769684680:ios:7875419036b5c1240737fd',
    messagingSenderId: '381769684680',
    projectId: 'business-app-f6f9b',
    databaseURL: 'https://business-app-f6f9b-default-rtdb.firebaseio.com',
    storageBucket: 'business-app-f6f9b.firebasestorage.app',
    iosBundleId: 'com.example.businessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfj_M34n9Bk6oPQl_fBlDdyOdR-1mfaxA',
    appId: '1:381769684680:ios:7875419036b5c1240737fd',
    messagingSenderId: '381769684680',
    projectId: 'business-app-f6f9b',
    databaseURL: 'https://business-app-f6f9b-default-rtdb.firebaseio.com',
    storageBucket: 'business-app-f6f9b.firebasestorage.app',
    iosBundleId: 'com.example.businessApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYQizWc7pVR5mUUmbNx75h6P2meGybPSw',
    appId: '1:381769684680:web:da88d8710371d18e0737fd',
    messagingSenderId: '381769684680',
    projectId: 'business-app-f6f9b',
    authDomain: 'business-app-f6f9b.firebaseapp.com',
    databaseURL: 'https://business-app-f6f9b-default-rtdb.firebaseio.com',
    storageBucket: 'business-app-f6f9b.firebasestorage.app',
    measurementId: 'G-S29NJKEKSE',
  );
}
